[package]
name = "wor"
version = "0.1.0"
authors = ["Alexander Greer <alexanderkeithgreer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
cursive = "0.19"
